In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/martinwg/ISA591/refs/heads/main/data/cereal.csv')
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [8]:
## X matrix (only predictors)
## SVD, PCA are unsupervised (no response)
X = df.drop(['name', 'mfr', 'type'], axis = 1)
X.head()

calories  protein  fat  sodium  fiber  carbo  sugars  potass  vitamins  \
0        70        4    1     130   10.0    5.0       6     280        25   
1       120        3    5      15    2.0    8.0       8     135         0   
2        70        4    1     260    9.0    7.0       5     320        25   
3        50        4    0     140   14.0    8.0       0     330        25   
4       110        2    2     200    1.0   14.0       8      -1        25   

   shelf  weight  cups     rating  
0      3     1.0  0.33  68.402973  
1      3     1.0  1.00  33.983679  
2      3     1.0  0.33  59.425505  
3      3     1.0  0.50  93.704912  
4      3     1.0  0.75  34.384843

In [3]:
## SVD (PCA) works the best
## too many predictors
## the predictors are correlated
## relationships with a response not important to describe

In [10]:
## SVD
## X = USV'
U, S, V = np.linalg.svd(X, full_matrices=False)

In [12]:
## U
## col(0) of U is a linear combination of calories, protein, fat, ....
## col(0) of U contains the MOST information about all 13 variables
## col(1) contains less information than col(0) but NOT included in col(0)
pd.DataFrame(U).head()

0         1         2         3         4         5         6   \
0 -0.129879  0.265631 -0.176881  0.000073 -0.104662  0.217281 -0.054376   
1 -0.063477  0.170911  0.172526 -0.073890  0.177335 -0.077479 -0.177153   
2 -0.185535  0.211523 -0.366813 -0.041286 -0.046606  0.100615 -0.018129   
3 -0.141873  0.324653 -0.262345 -0.026405 -0.281573  0.179781 -0.017329   
4 -0.102541 -0.146970  0.074648 -0.048709 -0.021358  0.127500 -0.091908   

         7         8         9         10        11        12  
0  0.080253  0.077720  0.059083 -0.056012  0.046347  0.031954  
1  0.201234 -0.149838 -0.096426 -0.288014 -0.197242 -0.141703  
2  0.012331 -0.151589 -0.085336  0.013740  0.082919  0.077736  
3  0.182430  0.316369  0.077408 -0.071789 -0.137275 -0.016287  
4  0.254901  0.051535  0.195119 -0.098778  0.026920 -0.132537

In [14]:
## V matrix
## recipe to get cols of U (weights of the linear combination)
## components of U
pd.DataFrame(V)

0         1         2         3         4         5         6   \
0  -0.445942 -0.010703 -0.004305 -0.752220 -0.009755 -0.060865 -0.029163   
1   0.036003  0.009027  0.002859 -0.525695  0.025494 -0.013520  0.002936   
2   0.810390  0.011403  0.008321 -0.387013 -0.017222  0.104537  0.055414   
3  -0.062950 -0.006630 -0.000903 -0.083997 -0.005001 -0.022188  0.026382   
4   0.346235 -0.020429  0.032272 -0.023889 -0.029750 -0.145802  0.178064   
5  -0.047198 -0.026074 -0.032756  0.017561  0.096893 -0.632286  0.731453   
6  -0.114193 -0.222306 -0.204979 -0.008740 -0.039573  0.718180  0.613120   
7  -0.003612 -0.451322  0.404727  0.000755  0.329452  0.026285 -0.042437   
8   0.041966 -0.295691 -0.228244 -0.003419  0.807307 -0.009990 -0.109011   
9  -0.022076  0.797386 -0.061535 -0.002501  0.454127  0.158235  0.106336   
10  0.040924 -0.140340 -0.855523  0.000365 -0.094196 -0.148338 -0.164970   
11  0.000151 -0.044895  0.055124  0.000877 -0.107888 -0.002969  0.022067   
12  0.007869 -0.021275 -0.033581  0.000363 -0.008211 -0.004996  0.005845   

          7         8         9         10        11        12  
0  -0.430612 -0.126970 -0.009157 -0.004317 -0.003328 -0.169872  
1   0.837198 -0.034579  0.005458  0.001205 -0.000661  0.138885  
2  -0.315489  0.101020  0.013297  0.006260  0.006913  0.262663  
3   0.031985  0.959391  0.009097 -0.000605 -0.001405 -0.257264  
4   0.103737 -0.225478 -0.006494 -0.000384 -0.005791 -0.873249  
5  -0.038044  0.024197  0.025606  0.008133  0.009803  0.220598  
6   0.017912 -0.020109  0.004333  0.009718  0.014303 -0.033765  
7  -0.009617 -0.007211  0.720091 -0.011116 -0.051392 -0.004492  
8  -0.016130  0.003198 -0.436317  0.016057 -0.055205 -0.031988  
9  -0.014770 -0.009418  0.317961 -0.013894 -0.114652 -0.050742  
10  0.003766 -0.007562  0.427565  0.033026 -0.065686 -0.018139  
11  0.000704  0.002794 -0.077297  0.078241 -0.985075  0.018229  
12  0.000934  0.000881 -0.011023 -0.995988 -0.077999  0.005592

In [16]:
## S
## How much information from the 13 columns is contained in each col of U
## S should be a matrix
np.diag(S)

array([[2.04056981e+03, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 6.68191257e+02, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.42850787e+02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.78836823e+02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+

### **Decomposition**

In [19]:
pd.DataFrame(U @ np.diag(S) @ V).head()

0    1             2      3     4     5             6      7   \
0   70.0  4.0  1.000000e+00  130.0  10.0   5.0  6.000000e+00  280.0   
1  120.0  3.0  5.000000e+00   15.0   2.0   8.0  8.000000e+00  135.0   
2   70.0  4.0  1.000000e+00  260.0   9.0   7.0  5.000000e+00  320.0   
3   50.0  4.0 -4.427440e-14  140.0  14.0   8.0  6.367521e-14  330.0   
4  110.0  2.0  2.000000e+00  200.0   1.0  14.0  8.000000e+00   -1.0   

             8    9    10    11         12  
0  2.500000e+01  3.0  1.0  0.33  68.402973  
1 -2.504845e-14  3.0  1.0  1.00  33.983679  
2  2.500000e+01  3.0  1.0  0.33  59.425505  
3  2.500000e+01  3.0  1.0  0.50  93.704912  
4  2.500000e+01  3.0  1.0  0.75  34.384843

In [20]:
X.head()

calories  protein  fat  sodium  fiber  carbo  sugars  potass  vitamins  \
0        70        4    1     130   10.0    5.0       6     280        25   
1       120        3    5      15    2.0    8.0       8     135         0   
2        70        4    1     260    9.0    7.0       5     320        25   
3        50        4    0     140   14.0    8.0       0     330        25   
4       110        2    2     200    1.0   14.0       8      -1        25   

   shelf  weight  cups     rating  
0      3     1.0  0.33  68.402973  
1      3     1.0  1.00  33.983679  
2      3     1.0  0.33  59.425505  
3      3     1.0  0.50  93.704912  
4      3     1.0  0.75  34.384843

## **THEORY OF PCA**

PCA is a generalization of SVD (it is SVD done on the cov matrix).

In [21]:
## new X with only first 3 cols of X
XR = X.iloc[:, :3]
XR

calories  protein  fat
0         70        4    1
1        120        3    5
2         70        4    1
3         50        4    0
4        110        2    2
..       ...      ...  ...
72       110        2    1
73       110        1    1
74       100        3    1
75       100        3    1
76       110        2    1

[77 rows x 3 columns]

In [22]:
## covariance matrix
## variances on the diagonals and covariances in the off-diagonals
## square and symmetric matrix
XR.cov()

calories   protein       fat
calories  379.630895  0.406699  9.777854
protein     0.406699  1.198565  0.229665
fat         9.777854  0.229665  1.012987

In [31]:
## sum the 3 variances
sum_vars = XR["calories"].var() + XR["protein"].var() + XR["fat"].var()
sum_vars

381.8424470266575

In [32]:
print(f'Variance of Calories : {XR["calories"].var()  / sum_vars }')
print(f'Variance of Protein  : {XR["protein"].var() / sum_vars}')
print(f'Variance of Fat      : {XR["fat"].var() / sum_vars}')

Variance of Calories : 0.9942082091095177
Variance of Protein  : 0.00313889826192571
Variance of Fat      : 0.002652892628556545


We want the variables to be **standardized** before we fit PCA, because higher units will mean more information.

In [26]:
XR['calories'].var()


379.63089542036903

In [33]:
## covariance is a measure of how the variables vary together
## -inf to inf (e.g., -1000 will depend on the units but it is negative linear relationship)
from statistics import covariance
cov_calories_protein = covariance(XR['calories'], XR['protein'])
cov_calories_protein

0.40669856459330167

In [34]:
## standardized covariance is called correlation
## correlation between calories and protein
## corr = cov /( sd_x1*sd_x2)
## -1 to 1 (standardized)
cov_calories_protein / (XR['calories'].std() * XR['protein'].std())

0.019066068232356945

In [35]:
XR.corr()

calories   protein       fat
calories  1.000000  0.019066  0.498610
protein   0.019066  1.000000  0.208431
fat       0.498610  0.208431  1.000000

In [37]:
## PCA is a decomposition of the covariance matrix

from sklearn.decomposition import PCA

## instance
pcaanalysis = PCA()
PCs = pcaanalysis.fit_transform(XR)

## how much variation the PCs keep
np.cumsum(pcaanalysis.explained_variance_ratio_)

array([0.99487025, 0.99824592, 1.        ])

In [41]:
## PCs is actually U
## the cols of U are called principal components
## PC1 contains information about calories, protein, fat
pd.DataFrame(PCs, columns = ['PC1', 'PC2', 'PC3']).head()

PC1       PC2       PC3
0 -36.869568  1.740237  0.294441
1  13.215869  1.803707  3.200462
2 -36.869568  1.740237  0.294441
3 -56.888699  1.575105 -0.160687
4   3.140714 -0.159852  1.047395

In [40]:
## The explained variance ratio is just S
pcaanalysis.explained_variance_ratio_

array([0.99487025, 0.00337567, 0.00175408])

In [42]:
## components is the V matrix
pcaanalysis.components_

array([[ 0.99966653,  0.00108926,  0.02579994],
       [-0.01088883,  0.92372212,  0.38290845],
       [-0.02341489, -0.3830617 ,  0.92342595]])

In [43]:
## how is the PC matrix made up?
XR.head(3)

calories  protein  fat
0        70        4    1
1       120        3    5
2        70        4    1

In [44]:
pd.DataFrame(PCs, columns = ['PC1', 'PC2', 'PC3']).head(3)

PC1       PC2       PC3
0 -36.869568  1.740237  0.294441
1  13.215869  1.803707  3.200462
2 -36.869568  1.740237  0.294441

In [46]:
## The PC1 (obs 1) is obtained as:
0.99966653*(70 - XR['calories'].mean()) + -0.01088883*(4 - XR['protein'].mean()) +  -0.02341489*(1 - XR['fat'].mean())

-36.88635167883117

In [47]:
## The PC1 (obs 2) is obtained as:
0.99966653*(120 - XR['calories'].mean()) + -0.01088883*(3 - XR['protein'].mean()) +  -0.02341489*(5 - XR['fat'].mean())

13.014204091168832

## **Visualization**

When you have too many predictors. You can visualize your data in a scatter plot. That visualization can share insights.

In [48]:
## check malware dataset
df = pd.read_csv('https://raw.githubusercontent.com/martinwg/ISA591/refs/heads/main/data/malware.csv')
df.head()

ACCESS_ALL_DOWNLOADS  ACCESS_CACHE_FILESYSTEM  ACCESS_CHECKIN_PROPERTIES  \
0                   0.0                      0.0                        0.0   
1                   0.0                      0.0                        0.0   
2                   0.0                      0.0                        0.0   
3                   0.0                      0.0                        0.0   
4                   0.0                      0.0                        0.0   

   ACCESS_COARSE_LOCATION  ACCESS_COARSE_UPDATES  ACCESS_FINE_LOCATION  \
0                     0.0                    0.0                   0.0   
1                     0.0                    0.0                   0.0   
2                     0.0                    0.0                   0.0   
3                     0.0                    0.0                   0.0   
4                     0.0                    0.0                   0.0   

   ACCESS_LOCATION_EXTRA_COMMANDS  ACCESS_MOCK_LOCATION  ACCESS_MTK_MMHW  \
0                             0.0                   0.0              0.0   
1                             0.0                   0.0              0.0   
2                             0.0                   0.0              0.0   
3                             0.0                   0.0              0.0   
4                             0.0                   0.0              0.0   

   ACCESS_NETWORK_STATE  ...  \
0                   1.0  ...   
1                   1.0  ...   
2                   1.0  ...   
3                   0.0  ...   
4                   0.0  ...   

   Landroid/telephony/TelephonyManager;->getLine1Number  \
0                                                1.0      
1                                                0.0      
2                                                0.0      
3                                                0.0      
4                                                0.0      

   Landroid/telephony/TelephonyManager;->getNetworkOperator  \
0                                                1.0          
1                                                0.0          
2                                                0.0          
3                                                1.0          
4                                                0.0          

   Landroid/telephony/TelephonyManager;->getNetworkOperatorName  \
0                                                1.0              
1                                                0.0              
2                                                0.0              
3                                                1.0              
4                                                0.0              

   Landroid/telephony/TelephonyManager;->getNetworkCountryIso  \
0                                                0.0            
1                                                1.0            
2                                                0.0            
3                                                1.0            
4                                                0.0            

   Landroid/telephony/TelephonyManager;->getSimOperator  \
0                                                0.0      
1                                                0.0      
2                                                0.0      
3                                                1.0      
4                                                0.0      

   Landroid/telephony/TelephonyManager;->getSimOperatorName  \
0                                                0.0          
1                                                0.0          
2                                                0.0          
3                                                0.0          
4                                                0.0          

   Landroid/telephony/TelephonyManager;->getSimCountryIso  \
0                                                0.0        
1                                                

In [49]:
## predicting whether this software is a malware or not

In [50]:
## drop missing
df.dropna(inplace = True)

In [51]:
## Create an ID
## for visualization we might need an ID, name, identifier
df['ID'] = pd.DataFrame(range(0, df.shape[0]+1   ))

In [52]:
## create X matrix
X = df.drop(['Label', 'ID'], axis = 1)

In [53]:
X.head()

ACCESS_ALL_DOWNLOADS  ACCESS_CACHE_FILESYSTEM  ACCESS_CHECKIN_PROPERTIES  \
0                   0.0                      0.0                        0.0   
1                   0.0                      0.0                        0.0   
2                   0.0                      0.0                        0.0   
3                   0.0                      0.0                        0.0   
4                   0.0                      0.0                        0.0   

   ACCESS_COARSE_LOCATION  ACCESS_COARSE_UPDATES  ACCESS_FINE_LOCATION  \
0                     0.0                    0.0                   0.0   
1                     0.0                    0.0                   0.0   
2                     0.0                    0.0                   0.0   
3                     0.0                    0.0                   0.0   
4                     0.0                    0.0                   0.0   

   ACCESS_LOCATION_EXTRA_COMMANDS  ACCESS_MOCK_LOCATION  ACCESS_MTK_MMHW  \
0                             0.0                   0.0              0.0   
1                             0.0                   0.0              0.0   
2                             0.0                   0.0              0.0   
3                             0.0                   0.0              0.0   
4                             0.0                   0.0              0.0   

   ACCESS_NETWORK_STATE  ...  \
0                   1.0  ...   
1                   1.0  ...   
2                   1.0  ...   
3                   0.0  ...   
4                   0.0  ...   

   Landroid/content/pm/PackageManager;->getInstalledPackages  \
0                                                0.0           
1                                                0.0           
2                                                0.0           
3                                                0.0           
4                                                0.0           

   Landroid/telephony/TelephonyManager;->getLine1Number  \
0                                                1.0      
1                                                0.0      
2                                                0.0      
3                                                0.0      
4                                                0.0      

   Landroid/telephony/TelephonyManager;->getNetworkOperator  \
0                                                1.0          
1                                                0.0          
2                                                0.0          
3                                                1.0          
4                                                0.0          

   Landroid/telephony/TelephonyManager;->getNetworkOperatorName  \
0                                                1.0              
1                                                0.0              
2                                                0.0              
3                                                1.0              
4                                                0.0              

   Landroid/telephony/TelephonyManager;->getNetworkCountryIso  \
0                                                0.0            
1                                                1.0            
2                                                0.0            
3                                                1.0            
4                                                0.0            

   Landroid/telephony/TelephonyManager;->getSimOperator  \
0                                                0.0      
1                                                0.0      
2                                                0.0      
3                                                1.0      
4                                                0.0      

   Landroid/telephony/TelephonyManager;->getSimOperatorName  \
0                                                0.0          
1                                      

In [54]:
from sklearn.decomposition import PCA

## instance
pcaanalysis = PCA()
PCs = pcaanalysis.fit_transform(X)

## how much variation the PCs keep
np.cumsum(pcaanalysis.explained_variance_ratio_)

array([0.23294643, 0.38808903, 0.48662199, 0.5669864 , 0.64616094,
       0.6853581 , 0.71781469, 0.74398068, 0.76605425, 0.78505593,
       0.80011155, 0.81323567, 0.82589633, 0.83794638, 0.84836312,
       0.85683067, 0.86459545, 0.87183872, 0.87878464, 0.88534453,
       0.89140117, 0.89686232, 0.90209292, 0.90697552, 0.91168547,
       0.91628956, 0.92037635, 0.92442541, 0.9283168 , 0.93180018,
       0.93515516, 0.93823149, 0.94123557, 0.9441795 , 0.94703726,
       0.9497431 , 0.95228507, 0.95477947, 0.95713209, 0.95942073,
       0.96145934, 0.9634643 , 0.96536316, 0.96716791, 0.96887711,
       0.97052945, 0.9720395 , 0.97351191, 0.97489174, 0.9762368 ,
       0.97749631, 0.97870325, 0.97984558, 0.98089962, 0.98185725,
       0.98280145, 0.98369978, 0.98456989, 0.98542227, 0.9862027 ,
       0.98693161, 0.98764199, 0.98830079, 0.98895294, 0.98953482,
       0.99010196, 0.99066486, 0.99118208, 0.99165994, 0.99211199,
       0.99253014, 0.99294226, 0.99331974, 0.99366782, 0.99399

In [55]:
## SCATTER PLOT OF THE FIRST 2 PCS
## very informative (like a scatter plot of 342 variables)
PCdf = pd.concat([df['ID'], pd.DataFrame(PCs[:, :2], columns = ['PC1', 'PC2'])] , axis = 1)
PCdf.head()

ID       PC1       PC2
0  0.0  2.508197 -0.994398
1  1.0 -0.155520 -0.470391
2  2.0 -0.130558 -0.165610
3  3.0  0.304022 -0.648425
4  4.0 -1.833204  0.737408

In [58]:
PCdf.dropna(inplace = True)

In [61]:
import plotly.express as px

#cereals.reset_index(inplace = True) # to avoid different indices
#PCdf = pd.concat([cereals['name'], pd.DataFrame(PCs[:,0:2], columns = ['PC1', 'PC2'])], axis = 1)

## change name for ID
fig = px.scatter(PCdf, x="PC1", y="PC2", text="ID", log_x=False, size_max=100, color= "ID")
fig.update_traces(textposition='top center')
fig.update_layout(title_text='Cereal Brands and Principal Components', title_x=0.5)
fig.show()


In [62]:
## 3785
df.loc[3785]

ACCESS_ALL_DOWNLOADS                                            0.0
ACCESS_CACHE_FILESYSTEM                                         0.0
ACCESS_CHECKIN_PROPERTIES                                       0.0
ACCESS_COARSE_LOCATION                                          0.0
ACCESS_COARSE_UPDATES                                           0.0
                                                             ...   
Landroid/telephony/TelephonyManager;->getSimCountryIso          0.0
Landroid/telephony/TelephonyManager;->getSimSerialNumber        0.0
Lorg/apache/http/impl/client/DefaultHttpClient;->execute        0.0
Label                                                       malware
ID                                                             3785
Name: 3785, Length: 243, dtype: object

In [ ]:
## Find anomalies in your data set
## using the scatter plot you can find obs that are far away from the rest